import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Excellent tution app",
  description: "Generated by create next app",
};

export default function WithNavLayout({ children }) {
  return (
    <section>
      <main>
        <Navbar />
        {children}
      </main>
    </section>
  );
}
